version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: virtual_table
      POSTGRES_USER: taco
      POSTGRES_PASSWORD: password